version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/" # Location of Terraform files
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/test/" # Location of go.mod file
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

