formatter: "markdown table" # this is requiredmarkdown table

sections:
  show:
    - requirements
    - providers
    - inputs
    - outputs
    - modules
    - resources

recursive:
  enabled: true
  path: modules
  include-main: true

output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

sort:
  enabled: true
  by: required

settings:
  anchor: true
  default: true
  escape: true
  indent: 2
  required: true
  sensitive: true
  type: true
